<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [<!ELEMENT root ANY><!ELEMENT item ANY><!ATTLIST item ID ID #REQUIRED><!ATTLIST item Explanation CDATA #IMPLIED>]><root>
<item ID="APPPATH">C:\Users\Administrator\workspace\nomvc\WebContent\</item>
<item ID="IL8N">en</item>
<item ID="DB_TYPE">sqlite</item>
<item ID="DB_HOST">NULL</item>
<item ID="DB_NAME">NULL</item>
<item ID="DB_USERNAME">NULL</item>
<item ID="DB_PASSWORD">NULL</item>
<item ID="DB_URL" Explanation="only in java need this"><![CDATA[jdbc:sqlite://localhost:3306/myapp?user=root&password=null]]></item>
<item ID="MODE">independent</item>
<item ID="ZONE" Explanation="see GB2260 , China-Standard">330281</item>
<item ID="ZONE4">3302</item>
<item ID="ZONE6">330281</item>
<item ID="ZONE8">33028101</item>
<item ID="reLoad">donothing</item>
</root>